#!/bin/sh

if [ ! -f "/usr/local/bin/pcp_stop_pgpool" ]; then
	mkdir -p /tmp/pgpool
	cd /tmp/pgpool
	
	wget http://www.pgpool.net/download.php?f=pgpool-II-3.3.2.tar.gz
	mv download.php\?f\=pgpool-II-3.3.2.tar.gz pgpool.tar.gz
	tar -xvf pgpool.tar.gz
	rm -f pgpool.tar.gz
	
	cd pgpool-*
	
	./configure
	make
	make install
fi