#! /bin/sh

if [ $# -ne 2 ]
then
    echo "pgpool_remote_start remote_host remote_datadir"
    exit 1
fi

DEST=$1
DESTDIR=$2

# Deploy a base backup
echo "cd $DESTDIR; tar zxf pgsql.tar.gz" | ssh $DEST
# Startup PostgreSQL server
echo "service postgresql restart" | ssh $DEST