#!/bin/sh

if [ ! -f "/usr/local/bin/pcp_stop_pgpool" ]; then
	/usr/bin/main-pgpool-install
	
	cd sql/pgpool-recovery
	make
	make install
	psql -f pgpool-recovery.sql template1
	psql -f pgpool-recovery.sql postgres
	psql -f pgpool-recovery.sql root
	cd ../pgpool-regclass
	make
	make install
	psql -f pgpool-regclass.sql template1
	psql -f pgpool-regclass.sql postgres
	psql -f pgpool-recovery.sql root
	rm -f -r /tmp/pgpool
fi