#!/bin/sh

# function to "declare" the database that exist
if [[ -n $(postgresql-check-db-dir /var/lib/pgsql/data) ]]; then
	echo "Need to initialize"
	rm -r -f /var/lib/pgsql/data
    chkconfig postgresql on
	/usr/bin/postgresql-setup initdb
	if [[ -n $(postgresql-check-db-dir /var/lib/pgsql/data) ]]; then
		if [[ "$#" == *"0"* ]];then
			sleep 1 m
			/usr/bin/postgresql_create 1
		fi
	else
		service postgresql restart
	fi
else
    echo "already init"
fi