#!/bin/sh

# function to "declare" the database that exist
if [[ -n $(postgresql-check-db-dir /var/lib/pgsql/data) ]]; then
	echo "Need to initialize"
	rm -r -f /var/lib/pgsql/data
    chkconfig postgresql on
	 /usr/bin/postgresql-setup initdb
	 service restart postgresql
else
    echo "already init"
fi